# Generated by Django 5.2.4 on 2025-07-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exam_question_studentexam_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='target_class',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
